// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AllRemainingTestsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void allRemainingTests() {
    // Test name: All Remaining Tests
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.flipkart.com//");
    // 2 | setWindowSize | 1536x816 | 
    driver.manage().window().setSize(new Dimension(1536, 816));
    // 3 | click | css=.\_1TOQfO > span | 
    driver.findElement(By.cssSelector(".\\_1TOQfO > span")).click();
    // 4 | type | css=.r4vIwl | 9326206722
    driver.findElement(By.cssSelector(".r4vIwl")).sendKeys("9326206722");
    // 5 | click | css=.QqFHMw | 
    driver.findElement(By.cssSelector(".QqFHMw")).click();
    // 6 | type | css=.\_5BVqVB:nth-child(1) | 6
    driver.findElement(By.cssSelector(".\\_5BVqVB:nth-child(1)")).sendKeys("6");
    // 7 | type | css=.I-qZ4M:nth-child(2) > .r4vIwl | 5
    driver.findElement(By.cssSelector(".I-qZ4M:nth-child(2) > .r4vIwl")).sendKeys("5");
    // 8 | type | css=.I-qZ4M:nth-child(3) > .r4vIwl | 1
    driver.findElement(By.cssSelector(".I-qZ4M:nth-child(3) > .r4vIwl")).sendKeys("1");
    // 9 | type | css=.I-qZ4M:nth-child(4) > .r4vIwl | 6
    driver.findElement(By.cssSelector(".I-qZ4M:nth-child(4) > .r4vIwl")).sendKeys("6");
    // 10 | type | css=.I-qZ4M:nth-child(5) > .r4vIwl | 4
    driver.findElement(By.cssSelector(".I-qZ4M:nth-child(5) > .r4vIwl")).sendKeys("4");
    // 11 | type | css=.I-qZ4M:nth-child(6) > .r4vIwl | 6
    driver.findElement(By.cssSelector(".I-qZ4M:nth-child(6) > .r4vIwl")).sendKeys("6");
    // 12 | mouseOver | linkText=Flight Bookings | 
    {
      WebElement element = driver.findElement(By.linkText("Flight Bookings"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 13 | mouseOut | linkText=Flight Bookings | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 14 | close |  | 
    driver.close();
    // 15 | close |  | 
    driver.close();
    // 16 | click | css=.\_1ch8e_:nth-child(6) .\_2puWtW | 
    driver.findElement(By.cssSelector(".\\_1ch8e_:nth-child(6) .\\_2puWtW")).click();
    // 17 | click | css=.cPHDOP:nth-child(9) .xcFiqU:nth-child(1) .xTaogf | 
    driver.findElement(By.cssSelector(".cPHDOP:nth-child(9) .xcFiqU:nth-child(1) .xTaogf")).click();
    // 18 | mouseOver | css=.cPHDOP:nth-child(2) div:nth-child(2) .\_4WELSP | 
    {
      WebElement element = driver.findElement(By.cssSelector(".cPHDOP:nth-child(2) div:nth-child(2) .\\_4WELSP"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 19 | mouseOut | css=.cPHDOP:nth-child(2) div:nth-child(2) .\_4WELSP | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 20 | mouseOver | css=.cPHDOP:nth-child(2) div:nth-child(2) .DByuf4 | 
    {
      WebElement element = driver.findElement(By.cssSelector(".cPHDOP:nth-child(2) div:nth-child(2) .DByuf4"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 21 | mouseOut | css=.cPHDOP:nth-child(2) div:nth-child(2) .DByuf4 | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 22 | mouseOver | css=.cPHDOP:nth-child(2) > .\_75nlfW > div:nth-child(1) .hl05eU | 
    {
      WebElement element = driver.findElement(By.cssSelector(".cPHDOP:nth-child(2) > .\\_75nlfW > div:nth-child(1) .hl05eU"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 23 | click | linkText=LIVPURE LIV-PEP-PRO-STAR. 7 L RO + UV + UF + Minerals W... | 
    vars.put("window_handles", driver.getWindowHandles());
    // 24 | selectWindow | handle=${win5835} | 
    driver.findElement(By.linkText("LIVPURE LIV-PEP-PRO-STAR. 7 L RO + UV + UF + Minerals W...")).click();
    // 25 | click | css=.IZexXJ | 
    vars.put("win5835", waitForWindow(2000));
    // 26 | click | css=.SibU2y .\_0DkuPH | 
    driver.switchTo().window(vars.get("win5835").toString());
    // 27 | click | css=.\_39kFie > .DOjaWF | 
    driver.findElement(By.cssSelector(".IZexXJ")).click();
    // 28 | click | css=.SibU2y .\_0DkuPH | 
    driver.findElement(By.cssSelector(".SibU2y .\\_0DkuPH")).click();
    // 29 | click | css=.SibU2y .\_0DkuPH | 
    driver.findElement(By.cssSelector(".\\_39kFie > .DOjaWF")).click();
    // 30 | click | css=.SibU2y .\_0DkuPH | 
    driver.findElement(By.cssSelector(".SibU2y .\\_0DkuPH")).click();
    // 31 | click | css=.SibU2y .\_0DkuPH | 
    driver.findElement(By.cssSelector(".SibU2y .\\_0DkuPH")).click();
    // 32 | click | css=.\_6gf9Ot | 
    driver.findElement(By.cssSelector(".SibU2y .\\_0DkuPH")).click();
    // 33 | click | css=.SibU2y .\_0DkuPH | 
    driver.findElement(By.cssSelector(".SibU2y .\\_0DkuPH")).click();
    // 34 | mouseOver | css=.XGZdnG:nth-child(1) > .IKoe2r | 
    driver.findElement(By.cssSelector(".\\_6gf9Ot")).click();
    // 35 | click | css=.\_9Wy27C > span | 
    driver.findElement(By.cssSelector(".SibU2y .\\_0DkuPH")).click();
    // 36 | mouseOver | css=.\_9Wy27C > span | 
    {
      WebElement element = driver.findElement(By.cssSelector(".XGZdnG:nth-child(1) > .IKoe2r"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 37 | mouseOver | linkText=Wishlist | 
    driver.findElement(By.cssSelector(".\\_9Wy27C > span")).click();
    // 38 | click | css=.zA2EfJ > span | 
    {
      WebElement element = driver.findElement(By.cssSelector(".\\_9Wy27C > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 39 | mouseOver | css=.zA2EfJ > span | 
    {
      WebElement element = driver.findElement(By.linkText("Wishlist"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 40 | mouseOut | css=.zA2EfJ > span | 
    driver.findElement(By.cssSelector(".zA2EfJ > span")).click();
    // 41 | click | css=.AuhJKm > span | 
    {
      WebElement element = driver.findElement(By.cssSelector(".zA2EfJ > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 42 | runScript | window.scrollTo(0,0) | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 43 | click | css=.QqFHMw | 
    driver.findElement(By.cssSelector(".AuhJKm > span")).click();
    // 44 | click | css=.QqFHMw | 
    js.executeScript("window.scrollTo(0,0)");
    // 45 | click | css=.\_0ofT-K | 
    driver.findElement(By.cssSelector(".QqFHMw")).click();
    // 46 | runScript | window.scrollTo(0,0) | 
    driver.findElement(By.cssSelector(".QqFHMw")).click();
    // 47 | click | css=.QqFHMw | 
    driver.findElement(By.cssSelector(".\\_0ofT-K")).click();
    // 48 | mouseOver | css=.QqFHMw | 
    js.executeScript("window.scrollTo(0,0)");
    // 49 | click | css=.W5mR4e | 
    driver.findElement(By.cssSelector(".QqFHMw")).click();
    // 50 | click | css=.yx2hEq:nth-child(9) > .AT0fUR | 
    {
      WebElement element = driver.findElement(By.cssSelector(".QqFHMw"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".W5mR4e")).click();
    driver.findElement(By.cssSelector(".yx2hEq:nth-child(9) > .AT0fUR")).click();
  }
}
